stages:
  - build_application_docker_image
  - redeploy

cache:
  paths:
    - node_modules/
      
build_application_docker_image:
  stage: build_application_docker_image
  tags:
   - docker-image-build
  script: 
   - "echo building $CI_REGISTRY_IMAGE" 
  variables:
   TO: $CI_REGISTRY_IMAGE:runner 
      
redeploy:
  stage: redeploy
  only:
  - master
  image: gitlab-registry.cern.ch/paas-tools/openshift-client:latest
  script: "oc import-image $APP_NAME --all=true --server=$SERVER --namespace $NAMESPACE --token=$IMAGE_IMPORT_TOKEN "

