-- Generated by Oracle SQL Developer REST Data Services 18.1.0.095.1630
-- Exported REST Definitions from ORDS Schema Version 3.0.11.180.12.34
-- Schema: ATLAS_DBMON   Date: Fri Aug 10 13:48:34 CEST 2018
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'ATLAS_DBMON',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'atlas_dbmon',
      p_auto_rest_auth      => FALSE);    

  ORDS.DEFINE_MODULE(
      p_module_name    => 'basic_info',
      p_base_path      => '/basic_info/',
      p_items_per_page =>  300,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'basic_info',
      p_pattern        => ':dbnameq/:dateq',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'basic_info',
      p_pattern        => ':dbnameq/:dateq',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  300,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT * FROM
(
  select distinct round(avg(dbhm.METRIC_VALUE) over (partition by dbhm.metric_id, dbhm.inst_id)) as metricAvgCount, dbhm.inst_id as instid, 
    dbmd.METRIC_NAME as metric, dbmd.METRIC_UNIT as unit, dbmt.threshold as threshold, dbmd.homepage_visible AS visible, dbs.DBNODES as NrOfNodes  
	from ATLAS_DBMON.DB_HIST_METRICS dbhm  
	join ATLAS_DBMON.DB_METRIC_DESC dbmd on dbhm.metric_id=dbmd.metric_id  
	join ATLAS_DBMON.DB_METRICS_THRESHOLD dbmt on (dbhm.metric_id=dbmt.metric_id and dbhm.dbname = dbmt.dbname)
    left join ATLAS_DBMON.DATABASES dbs on dbhm.dbname = dbs.DBNAME
    WHERE t_stamp > sysdate - (:dateq /(24*60))  AND UPPER(dbhm.dbname) = UPPER(:dbnameq)
   order by dbhm.inst_id
)
PIVOT
(
  MAX(metricAvgCount)
  FOR instid IN (1,2,3,4)
)
ORDER BY metric'
      );


  COMMIT; 
END;