-- Generated by Oracle SQL Developer REST Data Services 18.1.0.095.1630
-- Exported REST Definitions from ORDS Schema Version 3.0.11.180.12.34
-- Schema: DBMON_SCHEMA   Date: Fri Aug 10 13:49:34 CEST 2018
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'DBMON_SCHEMA',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'dbmon_schema',
      p_auto_rest_auth      => FALSE);    

  ORDS.DEFINE_MODULE(
      p_module_name    => 'schema_sessions',
      p_base_path      => '/schema_sessions/',
      p_items_per_page =>  300,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'schema_sessions',
      p_pattern        => ':db/:schema',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'schema_sessions',
      p_pattern        => ':db/:schema',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  300,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT NODE_ID, USERNAME, NUM_ACTIVE_SESS, NUM_SESS,
OSUSER, MACHINE, PROGRAM
FROM DBMON_SCHEMA.DB_SESS_DISTR 
WHERE db_name = UPPER(:db) AND USERNAME LIKE  CONCAT( UPPER(:schema), ''%'' ) 
AND t_stamp = (SELECT MAX(T_STAMP) 
FROM DBMON_SCHEMA.DB_SESS_DISTR WHERE DB_NAME = UPPER(:db))
ORDER BY 4 desc'
      );


  COMMIT; 
END;