-- Generated by Oracle SQL Developer REST Data Services 18.1.0.095.1630
-- Exported REST Definitions from ORDS Schema Version 3.0.11.180.12.34
-- Schema: DBMON_SCHEMA   Date: Fri Aug 10 13:50:13 CEST 2018
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'DBMON_SCHEMA',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'dbmon_schema',
      p_auto_rest_auth      => FALSE);    

  ORDS.DEFINE_MODULE(
      p_module_name    => 'session_info',
      p_base_path      => '/session_info/',
      p_items_per_page =>  250,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'session_info',
      p_pattern        => ':db',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'session_info',
      p_pattern        => ':db',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  250,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'Select af.USERNAME
, CASE af.NODE1 WHEN ''0/0'' THEN '' '' ELSE af.NODE1 END as NODE1
, CASE af.NODE2 WHEN ''0/0'' THEN '' '' ELSE af.NODE2 END as NODE2
, CASE af.NODE3 WHEN ''0/0'' THEN '' '' ELSE af.NODE3 END as NODE3
, CASE af.NODE4 WHEN ''0/0'' THEN '' '' ELSE af.NODE4 END as NODE4
, bs.ACTIVE_SESS, bs.SESS, af.SESS_LIMIT, bs.WORKLOAD, bs.TO_DISPLAY  from (
SELECT * FROM
(
    select node_id, username, 
    -- as workload,
    num_active_sess, num_sess, sess_limit, t_stamp
    from table(DBMON_SCHEMA.GET_SESS_DISTRIBUTION_DATA((:db)))
)
PIVOT
(
  MAX(NUM_ACTIVE_SESS || ''/'' || NUM_SESS),
  SUM(NUM_SESS) as NUM_SESSIONS
  FOR NODE_ID IN (1 as Node1,2 as Node2,3 as Node3,4 as Node4)
)
ORDER BY USERNAME) af


JOIN
(select USERNAME
, sum(NUM_ACTIVE_SESS) as ACTIVE_SESS
, sum(NUM_SESS) as SESS
, SESS_LIMIT
, (sum(NUM_SESS) / SESS_LIMIT) as WORKLOAD
,sum(NUM_ACTIVE_SESS) || ''/'' || sum(NUM_SESS) AS TO_DISPLAY 
from table(DBMON_SCHEMA.GET_SESS_DISTRIBUTION_DATA((:db)))
group by USERNAME, SESS_LIMIT) bs
ON af.USERNAME = bs.USERNAME'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'SessionInfo',
      p_pattern        => 'total/:db',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'SessionInfo',
      p_pattern        => 'total/:db',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  250,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select USERNAME
, sum(NUM_ACTIVE_SESS) as ACTIVE_SESS
, sum(NUM_SESS) as SESS
, SESS_LIMIT
, (sum(NUM_SESS) / SESS_LIMIT) as WORKLOAD
,sum(NUM_SESS) || ''/'' || SESS_LIMIT AS TO_DISPLAY 
from table(DBMON_SCHEMA.GET_SESS_DISTRIBUTION_DATA((:db)))
group by USERNAME, SESS_LIMIT;

-- NOT IN USE ANYMORE'
      );


  COMMIT; 
END;