-- Generated by Oracle SQL Developer REST Data Services 18.1.0.095.1630
-- Exported REST Definitions from ORDS Schema Version 3.0.11.180.12.34
-- Schema: ATLAS_DBMON   Date: Fri Aug 10 13:50:39 CEST 2018
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'ATLAS_DBMON',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'atlas_dbmon',
      p_auto_rest_auth      => FALSE);    

  ORDS.DEFINE_MODULE(
      p_module_name    => 'streams_info',
      p_base_path      => '/streams_info/',
      p_items_per_page =>  500,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'streams_info',
      p_pattern        => ':db/:node/:metric/:fromDate/:toDate',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'streams_info',
      p_pattern        => ':db/:node/:metric/:fromDate/:toDate',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  500,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT t_stamp, metric_value FROM ATLAS_DBMON.DB_HIST_METRICS 
WHERE T_STAMP >= TO_DATE((:fromDate), ''YYYY-MM-DD"T"HH24:MI'') 
AND T_STAMP < TO_DATE((:toDate), ''YYYY-MM-DD"T"HH24:MI'')
AND dbname = UPPER(:db) AND METRIC_ID = :metric AND INST_ID = :node order by 1'
      );


  COMMIT; 
END;