package atlas.dbmon.data;
// Generated Nov 24, 2015 11:28:57 AM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Databases generated by hbm2java
 */
@Entity
@Table(name="DATABASES"
    ,schema="DBMON_SCHEMA"
)
public class Databases implements java.io.Serializable {


     private String dbname;
     private BigDecimal position;
     private BigDecimal dbnodes;

    public Databases() {
    }

	
    public Databases(String dbname) {
        this.dbname = dbname;
    }
    public Databases(String dbname, BigDecimal position, BigDecimal dbnodes) {
       this.dbname = dbname;
       this.position = position;
       this.dbnodes = dbnodes;
    }
   
    @Id   
    @Column(name="DBNAME", unique=true, nullable=false, length=64)
    public String getDbname() {
        return this.dbname;
    }
    
    public void setDbname(String dbname) {
        this.dbname = dbname;
    }
    
    @Column(name="POSITION", precision=0)
    public BigDecimal getPosition() {
        return this.position;
    }
    
    public void setPosition(BigDecimal position) {
        this.position = position;
    }
    
    @Column(name="DBNODES", precision=0)
    public BigDecimal getDbnodes() {
        return this.dbnodes;
    }
    
    public void setDbnodes(BigDecimal dbnodes) {
        this.dbnodes = dbnodes;
    }



}


