package atlas.dbmon.data;
// Generated Nov 24, 2015 11:28:57 AM by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DbMetricDesc generated by hbm2java
 */
@Entity
@Table(name = "DB_METRIC_DESC", schema = "ATLAS_DBMON")
public class DbMetricDesc implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = -4371364816449083346L;

	private BigDecimal metricId;
	private String groupName;
	private BigDecimal groupId;
	private String metricName;
	private String metricUnit;
	private BigDecimal threshold;

	public DbMetricDesc() {
	}

	public DbMetricDesc(BigDecimal metricId) {
		this.metricId = metricId;
	}

	public DbMetricDesc(BigDecimal metricId, String groupName, BigDecimal groupId, String metricName, String metricUnit,
			BigDecimal threshold) {
		this.metricId = metricId;
		this.groupName = groupName;
		this.groupId = groupId;
		this.metricName = metricName;
		this.metricUnit = metricUnit;
		this.threshold = threshold;
	}

	@Id
	@Column(name = "METRIC_ID", unique = true, nullable = false, precision = 0)
	public BigDecimal getMetricId() {
		return this.metricId;
	}

	public void setMetricId(BigDecimal metricId) {
		this.metricId = metricId;
	}

	@Column(name = "GROUP_NAME", length = 64)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "GROUP_ID", precision = 0)
	public BigDecimal getGroupId() {
		return this.groupId;
	}

	public void setGroupId(BigDecimal groupId) {
		this.groupId = groupId;
	}

	@Column(name = "METRIC_NAME", length = 64)
	public String getMetricName() {
		return this.metricName;
	}

	public void setMetricName(String metricName) {
		this.metricName = metricName;
	}

	@Column(name = "METRIC_UNIT", length = 64)
	public String getMetricUnit() {
		return this.metricUnit;
	}

	public void setMetricUnit(String metricUnit) {
		this.metricUnit = metricUnit;
	}

	@Column(name = "THRESHOLD", precision = 0)
	public BigDecimal getThreshold() {
		return this.threshold;
	}

	public void setThreshold(BigDecimal threshold) {
		this.threshold = threshold;
	}

}
